export const AahkActivityDetail = {
    name: "AahkActivityDetail",
    properties: {
        _id: 'string',
        activityDetailGuid: "string",
        activityGuid: "string",
        locationCode: "string",
        locationDesc: "string",
        doorNo: "string",
        doorUnit: "string",
        isDeleted: "string",
        createdBy: "string",
        createdTimestamp: "date",
        updatedBy: "string",
        updatedTimestamp: "date",
        eformResultGuid: "string",
        bu: "string",
        cat: "string",
        status: "string",
        projGuid: "string",
        isSync: "string",
        testResult: "string"
    },
    primaryKey: "_id",
};