export const ActivityList = {
  name: 'ActivityDetail',
  properties: {
    _id: 'string',
    activityGuid: 'string',
    category: 'string',
    woNo: 'string',
    activityId: 'string',
    locationCode: 'string',
    locationDesc: 'string',
    startDatetime: 'date',
    endDatetime: 'date',
    isDeleted: 'string',
    createdBy: 'string',
    createdTimestamp: 'date',
    updatedBy: 'string',
    updatedTimestamp: 'date',
    completeD_PERCENTAGE: 'double',
  },
  primaryKey: '_id',
};
