export const EformResultSubDetails = {
  name: 'EformResultSubDetails',
  properties: {
    _id: 'string',
    eformResultSubDetailGuid: 'string',
    eformResultDetailGuid: 'string',
    eformResultGuid: 'string',
    eformDefineSubGuid: 'string',
    activityGuid: 'string',
    sectionGroupId: 'string',
    sectionTitle: 'string',
    sectionSubtitle: 'string',
    sectionSort: 'double',
    subSectionGroupId: 'string',
    subSectionTitle: 'string',
    subHeader1: 'string',
    subFormType1: 'string',
    subAnsOption1: 'string',
    subAns1: 'string',
    subHeader2: 'string',
    subFormType2: 'string',
    subAnsOption2: 'string',
    subAns2: 'string',
    sort: 'double',
    updatedBy: 'string?',
    updatedTimestamp: 'date?',
  },
  primaryKey: '_id',
};
