export const EformResultDetail = {
    name: "EformResultDetail",
    properties: {
        _id: 'string',
        eformResultDetailGuid: "string",
        eformResultGuid: "string",
        eformDefineGuid: "string",
        activityGuid: "string",
        sectionGroupId: "string",
        sectionTitle: "string",
        sectionSubtitle: "string",
        sectionSort: "double",
        header1: "string",
        formType1: "string",
        ansOption1: "string",
        ans1: "string",
        header2: "string",
        formType2: "string",
        ansOption2: "string",
        ans2: "string",
        sort: "double",
        updatedBy: "string",
        updatedTimestamp: "date?"
    },
    primaryKey: "_id",
};